# Generated by Django 5.0 on 2023-12-17 10:05

from django.db import migrations

def populate_products(apps, schema_editor):
    # populate 'products' table with 5 products
    Product = apps.get_model('products', 'Product')
    Product.objects.create(name='Product 1', price=10, description='Product 1 description')
    Product.objects.create(name='Product 2', price=20, description='Product 2 description')
    Product.objects.create(name='Product 3', price=30, description='Product 3 description')
    Product.objects.create(name='Product 4', price=40, description='Product 4 description')
    Product.objects.create(name='Product 5', price=50, description='Product 5 description')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_products),
    ]
