# Generated by Django 5.0 on 2023-12-17 10:05

from django.db import migrations


def populate_products(apps, schema_editor):
    # populate 'products' table with 5 products
    product = apps.get_model('products', 'Product')

    product.objects.create(
        name='Banana', 
        price=0.50, 
        description='Potassium has never looked this ap-PEAL-ing',
        )
    product.objects.create(
        name='Red Chilli', 
        price=0.55, 
        description='"Don\'t cha wish your girlfriend was hot like me?"',
        )
    product.objects.create(
        name='Cinnamon', 
        price=2.10, 
        description='I could never for the life of me spell this word correctly',
        )
    product.objects.create(
        name='Eggs', 
        price=3.00, 
        description='An eggcellent source of protein',
        )
    product.objects.create(
        name='Garlic', 
        price=50, 
        description='Perfect for warding off vampires',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_products),
    ]
